
export enum OrdenEnum {
   CREATE_ORDEN_START = 'CREATE_ORDEN_START',
   CREATE_ORDEN_SUCCESS = 'CREATE_ORDEN_SUCCESS',
   CREATE_ORDEN_ERROR = 'CREATE_ORDEN_ERROR',

   DELETE_ORDEN_START = 'DELETE_ORDEN_START',
   DELETE_ORDEN_SUCCESS = 'DELETE_ORDEN_SUCCESS',
   DELETE_ORDEN_ERROR = 'DELETE_ORDEN_ERROR',

   ADD_ORDEN_DETAIL_START = 'ADD_ORDEN_DETAIL_START',
   ADD_ORDEN_DETAIL_SUCCESS = 'ADD_ORDEN_DETAIL_SUCCESS',
   ADD_ORDEN_DETAIL_ERROR = 'ADD_ORDEN_DETAIL_ERROR'
}